export const PATHS = {
  HOME: "/",
  WELCOME: "/",
  AUTH: {
    WELCOME: "/auth",
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    FORGOT_PASSWORD: "/auth/forgot-password",
    CHECK_EMAIL: "/auth/check-email",
    RESET_PASSWORD: "/auth/reset-password",
    RESET_PASSWORD_WITH_TOKEN: "/auth/reset-password/:token",
    RESET_PASSWORD_PUBLIC_QUERY: "/reset-password",
    RESET_PASSWORD_PUBLIC: "/reset-password/:token",
    RESET_PASSWORD_LARAVEL: "/password/reset/:token",
    RESET_PASSWORD_API: "/api/auth/reset-password/:token",
    PASSWORD_CHANGED: "/auth/password-changed",
    EMAIL_VERIFICATION_SENT: "/auth/email-verification-sent",
    VERIFY_EMAIL: "/auth/verify-email/:id/:hash",
    VERIFY_EMAIL_PUBLIC: "/verify-email/:id/:hash",
    VERIFY_EMAIL_LARAVEL: "/email/verify/:id/:hash",
    VERIFY_EMAIL_API: "/api/auth/verify-email/:id/:hash",
    EMAIL_VERIFIED: "/auth/email-verified",
    EMAIL_VERIFIED_PUBLIC: "/email-verified",
  },
};
